### PR TITLE
Added a method to split by space instead of using regex to make token…

### PR DESCRIPTION
**Pull request by jpark-dev**
Using regular expression with look-ahead/look-behind to split tokens is expensive. (http://stackoverflow.com/questions/9831034/poor-performance-speed-of-regex-with-lookahead)

Since the reason we use look-ahead/look-behind is to keep spaces, I replaced it with a custom function.
In my case, it reduced the time to tokenize 1000 documents from 39 seconds to 17 seconds.

### CODE REVIEW

**Comment by nlpenguin** [comment]
Thank! This looks great. Could you please make sure `mvn test` succeeds?

**Comment by nlpenguin** [comment]
@caniszczyk, could you please update Travis to run on Java 8? It has been broken for a while. Thanks in advance!

**Comment by jpark-dev** [comment]
@nlpenguin Thanks for reminding me of the tests!
Because I changed to group continuous spaces into one Space token, it broke one test cases(and one another because it somewhat changed the order of outputs of extrace phrases function). I updated those tests and added one test to KoreanChunkerTest.scala to check space tokens.
All tests passed now. 

Results :

Tests run: 86, Failures: 0, Errors: 0, Skipped: 0

**Comment by nlpenguin** [comment]
LGTM

**Comment by nlpenguin** [comment]
@jpark-dev  Thank you so much for your *heroic* contribution!!

I will publish the new version by Friday.

**Comment by jpark-dev** [comment]
Thanks for the merge, and thanks for the library. :)

**Pull request merged**
